### PR TITLE
New hero portraits

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR redraw the hero portraits. All the old portraits were plagiarism. I have retrieved them on the internet. The new ones have been created with Stable Diffusion XL with the Digital Art option:
https://google-sdxl.hf.space

Here are the prompts:

* Agnes - Face of a medieval male adventurer, close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:10)
* Agrenal - Face of a medieval blond female bard, laughing, close to the nature, from side, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:1000), (ugly:100), (worst quality:100), (drawing:500)
* Anastasia - Artistic portrait of the face of a medieval blonde female druid close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:100)
* Belinda - Artistic portrait of the face of a medieval female writer close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:100)
* Ceretus - Face of a medieval male warrior, close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:100), (ugly:100), (worst quality:100), (drawing:10)
* Hanna - [[[[[roughly drawn]]]]] portrait of the face of a female gardian close to the nature, from side, fighting, in a dark atmosphere, with play of light, contrast, artwork, (bad proportion)
* Julian - [[[[[roughly drawn]]]]] portrait of the face of a blonde medieval male gardian, from side, fighting, in a dark atmosphere, with play of light, contrast, artwork, (bad proportion)
* Karen - Face of a medieval female warrior, close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:1000), (ugly:100), (worst quality:100), (drawing:500)
* Ken - Face of a medieval man, terrified, close to the nature, from side, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:1000), (ugly:1000), (worst quality:100)
* Kulkin - [[[[[roughly drawn]]]]] portrait of the face of a male halfling, from side, fighting, in a magical atmosphere, (with play of light), artwork, bad proportion
* Lorenzo - Face of a medieval female guardian, who loves flowers, close to the nature, from side, fighting, in a dark atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:10)
* Niclas - Portrait of the face of a medieval male elf guardian close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, artistic, (bad proportions), (worst quality), ((ugly))
* Palema - Artistic portrait of the face of a medieval female elf adventurer close to the nature, from side, fighting, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:100)
* Polly - Face of a medieval woman, (looking back:10), close to the nature, from side, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:1000), (ugly:1000), (worst quality:100), (drawing:500)
* Renata - Artistic portrait of the face of a medieval female blonde bard close to the nature, from side, fighting, in a battle atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:100)
* Terence - Face of a medieval male adventurer, shouting, close to the nature, from side, in a magic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:20), (ugly:100), (worst quality:100)
* Wildhayen - Face of a medieval male lord, close to the nature, with a cap, from side, fighting, in a mystic atmosphere, with play of light, contrast, artwork, computer-aided, (bad proportions:1000), (ugly:1000), (worst quality:100), (drawing:500)

Negative prompt - black and white, monochrome, grayscale, symetrical view, symetric view, tiling, poorly drawn hands, poorly drawn feet, out of frame, extra limbs, body out of frame, bad anatomy, draft, watermark, grainy, signature, cut off, empty background, (detailled:100), (detail:100), (photo:100), (photography:100)

### CODE REVIEW

**Comment by misiokles** [comment]
It's @by003 decision.

**Comment by Fabrice-TIERCELIN** [comment]
@by003, tell me if there is a problem with this PR. All the content can be reworked. I wanna say, all the heroes should not be human.

**Comment by by003** [comment]
I have not finished the update of preserve yet, but it will be soon. I think portrait is not a big problem, if you have a better plan, just do this.

**Comment by Fabrice-TIERCELIN** [comment]
@by003, for now, I haven't any other plan. Let's merge it and perhaps improve it in the future if we find something better.

**Pull request merged**
