### PR TITLE
Remix the town theme

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR remixes the town theme. It makes the end more dynamic and less sleepy.

### CODE REVIEW

**Comment by by003** [comment]
There will be a big update in Preserve near the end of the year.
But I think previous Town theme is good, it is an original composition.

**Comment by Fabrice-TIERCELIN** [comment]
We will see together what to do in six monthes. We don't even know what the IAs will be able to do. The best case would be an IA where you input the original composition and it remixes it so that we could improve the quality and it's the continuity of the original work.

**Comment by Fabrice-TIERCELIN** [comment]
It's good news to have new designs for _Preserve_ 🙂, @by003. There are some perspective issues in the town screen. Can you save the images used for the dweling buildings so that it would ease me to update the dweling buildings on the map? Also I recommend you to take the shadow directions into account. If someone wants to fix it after, they will have to redo everything😭

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, perhaps, you have missed this PR

**Comment by misiokles** [comment]
I have not missed, but waiting for Ben's approval. Can you make PR for 1.5 branch?

**Comment by misiokles** [comment]
Ah, ok. Now I see that Ben likes it.

**Comment by Fabrice-TIERCELIN** [comment]
@by003, I have gathered all the most recent tools I know to draw a town screen [here](https://wiki.vcmi.eu/How_to_create_a_town_mod).

**Comment by by003** [comment]
Thanks, I have already done new town screen.

https://github.com/user-attachments/assets/de346de8-1a88-4b33-8147-f0907ea2f5e4

**Comment by Fabrice-TIERCELIN** [comment]
OK, if you are rendering creatures, I have two tips I haven't mentioned in the wiki:

- For AI, you can use [_Stable Fast 3D_](https://huggingface.co/spaces/stabilityai/stable-fast-3d)
- For _Blender_: render the images without background by selecting png RVBA
image
and disabling background
image
Then, in _GIMP_, apply an Alpha threeshold:
image

It avoids to render creatures with ugly dark border

**Comment by by003** [comment]
Oh cool. 
I have a creature bmp here but many of AI generator cannot do it well.
If you would like to help me, you can try to generate an idle action or other actions. 

rrt

**Comment by by003** [comment]
@Fabrice-TIERCELIN 
Could you help me to make moving and idle animations from this picture?
I have tried several times from AI.

**Comment by Fabrice-TIERCELIN** [comment]
I will look at it, @by003

**Comment by by003** [comment]
Thanks, I remade some details
image

**Comment by Fabrice-TIERCELIN** [comment]
Is this prompt a good description, @by003?

`60 years old Caucasian male wizard, green and yellow tunic, helmet with brown horns, white beard, golden epaulettes, long brown stick with a lamp, belt, brown shoes, serious mood, uniform black background`

**Comment by by003** [comment]
> Is this prompt a good description, @by003?
> 
> `60 years old Caucasian male wizard, green and yellow tunic, helmet with brown horns, white beard, golden epaulettes, long brown stick with a lamp, belt, brown shoes, serious mood, uniform black background`

@Fabrice-TIERCELIN I think it is good.

**Comment by Fabrice-TIERCELIN** [comment]
Improved prompt:

`60 years old Caucasian male wizard, green and yellow tunic, grey metal round helmet with brown horns, white beard, golden round epaulettes, long brown stick with a lamp, belt, brown shoes, looking at the right, serious mood, uniform black background, photorealistic, realistic`

Input image for _Stable Video Diffusion_ / _Animate LCM_:
for_svd

Input image for _Cinemo_ / _ToonCrafter_:
for_cinemo

**Comment by by003** [comment]
Thanks I will try

**Comment by Fabrice-TIERCELIN** [comment]
Here are the best parameters I have found:

1. Go to _Cinemo_ [here](https://huggingface.co/spaces/brokerrobin/Cinemo) or [here](https://huggingface.co/spaces/maxin-cn/Cinemo)
2. Upload the _"Image for Cinemo"_
3. In _Prompt_, paste `Wizard waiting, video looping, seamless looping`
3. In _Negative prompt_, paste `low quality, object appearing, object disappearing, object transformation, object distortion, flexible object`
4. In _Sampling steps_, set `128`
4. In _Motion Intensity_, set `3`
4. In _Seed_, set a different value for each generation
5. Click on _Generate_
4. Change the  _Seed_
6. Wait an hour before trying again
7. Generate from the other url to avoid quota penalties

It's not a big problem if it doesn't loop seamlessly because we may manage to fix it with _ToonCrafter_.

**Comment by by003** [comment]
Hello @Fabrice-TIERCELIN 
Could you help me to make a terrain music of Ice sheet?
I tried to generate from AI, but it is not so good.

**Comment by Fabrice-TIERCELIN** [comment]
I will look at it but I already have to finish the _Stardust_ theme. You can start with a prompt like this: `Ice, winter, Instrumental, 160 bpm, Cinematic classical`.

**Comment by Fabrice-TIERCELIN** [comment]
Here is the best animation I have obtained for _"Idle"_ animation:

https://github.com/user-attachments/assets/8517e52a-0ffd-4701-b040-05b1e4f35e60

And here is the best animation I have obtained for _"Mouse over"_ animation:

https://github.com/user-attachments/assets/6b46388b-adc9-4b6d-a2f9-5fe92431eb0b

To convert the video to `.png` images, I use _Blender_ (there are simpler ways but I have _Blender_ already installed):

1. Start an animation
2. In output, select png, select the number of frames as the end, select the height and the width of the video and set the same fps
3. Open the _Video sequence_ view
4. Drag and drop the video
5. Click on _Render_ / _Render the animation_

In _GIMP_, I resize and replace the background:

1. I select the border with a border of 2px
2. I add an alpha layer
3. I invert the selection
4. I remove the selection
6. Then I resize the canva from 512x320 to 146x260, centering the image
5. I rescale to /2 (so fourth less pixels), so that the image is 73x130
6. I apply the threeshold on the transparency by clicking on _Layer_ -> _Transparency_ -> _Alpha threeshold_

This way, it should fit this black rectangle:
black_background

If it's the case, the animation will fit seamlessly with the remaining images.

**Pull request merged**
