### PR TITLE
Display Centamonth instead of Halfing

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR uses Centamonthes as level 1 creatures because the Halfings already exist in _Armageddon's Blade_.

@kdmcser, @heroesiiifan, my update of the Chinese and German translations may be plenty of mistakes.

### CODE REVIEW

**Comment by misiokles** [comment]
I don't want to change line-up without Ben Yan permission :(

**Comment by Fabrice-TIERCELIN** [comment]
@by003, do you agree?

The idea is to avoid that a player installs the mod then the first thing the player will see is the Halfing and the player thinks _"Ah, they don't manage to create their own creatures. VCMI are not great mods."_

I can recycle Hobbits in Axolotl creature pack.

**Comment by by003** [comment]
You can change it now. I am planning for new units but it will not be finished for several days.

**Comment by kdmcser** [comment]
@Fabrice-TIERCELIN I think your translation is very well. You can also ask Ben Yan for Chinese translation advice when you want to change his mods.

**Pull request merged**
